#Docker 컨테이너를 정의하고 관리하기 위해 구성 파일
#여러 컨테이너와 한 곳에 정리 할 수 있게 해줌
#파일 버전
version: "3"
#services를 컨테이너를 정의
services:
  node-service:
    container_name: node-service
    build: .
    restart: always
    ports:
      - "8000:8000"