#Docker 컨테이너를 정의하고 관리하기 위해 구성 파일
#여러 컨테이너와 한 곳에 정리 할 수 있게 해줌
#파일 버전
version: '3'
#services를 컨테이너를 정의
services:
#web은 서비스의 이름
  web:
  #Docker이미지를 빌드할 때 사용할 지정. '.'은 현재 디렉토리(즉 지금 docker-compose.yml파일 위치)
  #이 설정은 해당 디렉토리의 Dockerfile을 사용하여 이미지를 빌드하라는 의미
    build: .
    #사용자는 8080 포트로 접속
    #실제 처리는 컨테이너 내의 8000 포트에서 이루어짐
    #8080과 8000 포트 사이의 통신은 Docker의 포트 매핑에 의해 이루어짐
    #사용자의 요청과 서버의 응답을 중개하는 역할
    ports:
      - "8080:8000"