openapi: 3.0.0
info:
  title: For me
  description: 설문지 폼 커스터마이징할 수 있게 해주는 api
  version: 0.1.9

servers:
  - url: http://localhost:8000

tags:
  - name: Backend endpoints

paths:
  /api/surveys:
    post:
      tags:
        - POST
      summary: 질문 생성 API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 사용자 ID
                title:
                  type: string
                  description: 설문조사 제목
                open:
                  type: boolean
                  description: 설문 공개 여부
                font:
                  type: string
                  description: 폰트 설정
                color:
                  type: string
                  description: 설문조사 색깔
                botton_style:
                  type: string
                  description: 버튼 스타일
                main_image_url:
                  type: string
                  description: 메인 이미지 url
                deadline:
                  type: date-time
                  description: 설문조사 마감 기간
                questions:
                  type: array
                  item:
                    type: object
                    properties:
                      type:
                        type: string
                        description: 질문 타입 (MULTIPLE_CHOICE, SUBJECTIVE_QUESTION, CHECKBOX, DROPDOWN)
                        enum:
                          - MULTIPLE_CHOICE
                          - SUBJECTIVE_QUESTION
                          - CHECKBOX
                          - DROPDOWN
                      content:
                        type: string
                        description: 질문 내용
                      image_url:
                        type: string
                        description: 질문 관련 이미지 url
                      choices:
                        type: array
                        item:
                          type: object
                          properties:
                            type: string
                            description: 선택지 내용
      responses:
        '201':
          description: 설문조사 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
                  surveyId:
                    type: integer
                    description: 생성된 설문조사의 ID
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지

  /api/surveys/{id}/forms:
    get:
      tags:
        - GET
      summary: 폼 모아보기 API
      description: 특정 사용자 ID에 속한 폼 템플릿을 모아서 보여주는 API입니다.
      parameters:
        - name: id
          in: path
          required: true
          description: 사용자 ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
                  total_count:
                    type: integer
                    description: 총 설문 템플릿 수
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류

  /api/surveys/{id}/join:
    get:
      tags:
        - GET
      summary: Get answered surveys of a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The user ID
      responses:
        '200':
          description: A list of surveys answered by the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
        '404':
          description: No answered surveys found for this user
        '500':
          description: Internal server error

components:
  schemas:
    Survey:
      type: object
      properties:
        id:
          type: integer
          description: 설문 ID
        title:
          type: string
          description: 설문 제목
        main_image_url:
          type: string
          description: 메인 이미지 URL
        created_at:
          type: string
          format: date-time
          description: 생성된 날짜와 시간
