openapi: 3.0.0
info:
  title: For me
  description: 설문지 폼 커스터마이징할 수 있게 해주는 API
  version: 0.1.9

servers:
  - url: http://localhost:8000

paths:
  /api/surveys:
    post:
      tags:
        - POST
      summary: 질문 생성 API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 사용자 ID
                title:
                  type: string
                  description: 설문조사 제목
                open:
                  type: boolean
                  description: 설문 공개 여부
                font:
                  type: string
                  description: 폰트 설정
                color:
                  type: string
                  description: 설문조사 색깔
                button_style:
                  type: string
                  description: 버튼 스타일
                main_image_url:
                  type: string
                  description: 메인 이미지 URL
                deadline:
                  type: string
                  format: date-time
                  description: 설문조사 마감 기간
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: 질문 타입 (MULTIPLE_CHOICE, SUBJECTIVE_QUESTION, CHECKBOX, DROPDOWN)
                        enum:
                          - MULTIPLE_CHOICE
                          - SUBJECTIVE_QUESTION
                          - CHECKBOX
                          - DROPDOWN
                      content:
                        type: string
                        description: 질문 내용
                      image_url:
                        type: string
                        description: 질문 관련 이미지 URL
                      choices:
                        type: array
                        items:
                          type: object
                          properties:
                            option:
                              type: string
                              description: 선택지 내용
      responses:
        '201':
          description: 설문조사 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
                  surveyId:
                    type: integer
                    description: 생성된 설문조사의 ID
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지

  /api/surveys/{id}/forms:
    get:
      tags:
        - GET
      summary: 폼 모아보기 API
      description: 특정 사용자 ID에 속한 폼 템플릿을 모아서 보여주는 API입니다.
      parameters:
        - name: id
          in: path
          required: true
          description: userId
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
                  total_count:
                    type: integer
                    description: 총 설문 템플릿 수
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류

  /api/surveys/{id}/join:
    get:
      summary: '내가 답변한 설문지'
      tags:
        - GET
      operationId: 'showAnsweredSurveys'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of the user'
          required: true
          schema:
            type: 'integer'
        - name: 'page'
          in: 'query'
          description: 'Page number'
          required: false
          schema:
            type: 'integer'
        - name: 'limit'
          in: 'query'
          description: 'Number of answered surveys to return per page'
          required: false
          schema:
            type: 'integer'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  surveys:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/Survey'
                  totalPages:
                    type: 'integer'
        '404':
          description: 'No answered surveys found for this user'
        '500':
          description: 'Server error'

  /api/surveys/{id}:
    put:
      summary: 설문 수정 API
      tags:
        - PUT
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: serveyId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: 사용자 ID
                title:
                  type: string
                  description: 설문조사 제목
                open:
                  type: boolean
                  description: 설문 공개 여부
                font:
                  type: string
                  description: 폰트 설정
                color:
                  type: string
                  description: 설문조사 색깔
                buttonStyle:
                  type: string
                  description: 버튼 스타일
                mainImageUrl:
                  type: string
                  description: 메인 이미지 URL
                deadline:
                  type: string
                  format: date-time
                  description: 설문조사 마감 기간
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: 질문 타입 (MULTIPLE_CHOICE, SUBJECTIVE_QUESTION, CHECKBOX, DROPDOWN)
                        enum:
                          - MULTIPLE_CHOICE
                          - SUBJECTIVE_QUESTION
                          - CHECKBOX
                          - DROPDOWN
                      content:
                        type: string
                        description: 질문 내용
                      imageUrl:
                        type: string
                        description: 질문 관련 이미지 URL
                      choices:
                        type: array
                        items:
                          type: object
                          properties:
                            option:
                              type: string
                              description: 선택지 내용
      responses:
        '200':
          description: 설문 수정 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
                  updatedSurvey:
                    type: object
                    properties:
                      userId:
                        type: integer
                        description: 사용자 ID
                      title:
                        type: string
                        description: 설문조사 제목
                      open:
                        type: boolean
                        description: 설문 공개 여부
                      font:
                        type: string
                        description: 폰트 설정
                      color:
                        type: string
                        description: 설문조사 색깔
                      buttonStyle:
                        type: string
                        description: 버튼 스타일
                      mainImageUrl:
                        type: string
                        description: 메인 이미지 URL
                      deadline:
                        type: string
                        format: date-time
                        description: 설문조사 마감 기간
                      updatedAt:
                        type: string
                        format: date-time
                        description: 설문 수정 시간
        '403':
          description: 접근 및 수정 권한이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '404':
          description: 설문을 찾을 수 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '500':
          description: 설문 수정 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지

  /api/surveys/{id}/all:
    get:
      summary: '전체 설문지 조회'
      tags:
        - GET
      operationId: 'showAllSurveys'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of the user'
          required: true
          schema:
            type: 'integer'
        - name: 'page'
          in: 'query'
          description: 'Page number'
          required: false
          schema:
            type: 'integer'
        - name: 'limit'
          in: 'query'
          description: 'Number of surveys to return per page'
          required: false
          schema:
            type: 'integer'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: 'object'
                properties:
                  surveys:
                    type: 'array'
                    items:
                      $ref: '#/components/schemas/Survey'
                  totalPages:
                    type: 'integer'
        '404':
          description: 'No surveys found'
        '500':
          description: 'Server error'

  /api/surveys/{id}/urls:
    get:
      tags:
        - GET
      summary: 설문조사의 URL을 반환합니다.
      description: 특정 설문조사(survey)의 URL을 가져옵니다.
      parameters:
        - in: path
          name: id
          required: true
          description: serveyId
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 URL을 가져왔을 때의 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: 'www.asdasdasdasdasd.com/asddasd'
        '404':
          description: 설문조사를 찾을 수 없을 때의 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '설문이 존재하지 않습니다.'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'URL을 생성하는데 실패하였습니다'

    delete:
      summary: 설문 삭제 API
      tags:
        - DELETE
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 삭제할 설문의 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: 사용자 ID
      responses:
        '200':
          description: 설문 및 관련 데이터 삭제 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
        '403':
          description: 설문 삭제 권한이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '404':
          description: 삭제할 설문이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '500':
          description: 설문 삭제 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지

  /api/surveys/{id}/results:
    get:
      summary: '설문지 결과 조회'
      tags:
        - GET
      operationId: 'getSurveyResult'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'ID of the survey to fetch'
          required: true
          schema:
            type: 'integer'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyResult'
        '404':
          description: 'Survey not found'
        '500':
          description: 'Server error'

components:
  schemas:
    SurveyResult:
      type: 'object'
      properties:
        user_name:
          type: 'string'
        title:
          type: 'string'
        open:
          type: 'boolean'
        created_at:
          type: 'string'
          format: 'date-time'
        updated_at:
          type: 'string'
          format: 'date-time'
        deadline:
          type: 'string'
          format: 'date-time'
        questions:
          type: 'array'
          items:
            $ref: '#/components/schemas/Question'
    Question:
      type: 'object'
      properties:
        question_id:
          type: 'integer'
        type:
          type: 'string'
        content:
          type: 'string'
        image_url:
          type: 'string'
        choices:
          type: 'array'
          items:
            $ref: '#/components/schemas/Choice'
        answers:
          type: 'array'
          items:
            $ref: '#/components/schemas/Answer'
    Choice:
      type: 'object'
      properties:
        choice_id:
          type: 'integer'
        option:
          type: 'string'
        count:
          type: 'integer'
    Answer:
      type: 'object'
      properties:
        answer_id:
          type: 'integer'
        content:
          type: 'string'
        objContent:
          type: 'string'
