openapi: 3.0.0
info:
  title: For me
  description: 설문지 폼 커스터마이징할 수 있게 해주는 API
  version: 0.1.9
servers:
  - url: http://localhost:8000
paths:
  /api/surveys:
    post:
      tags:
        - POST
      summary: 질문 생성 API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 사용자 ID
                title:
                  type: string
                  description: 설문조사 제목
                open:
                  type: boolean
                  description: 설문 공개 여부
                font:
                  type: string
                  description: 폰트 설정
                color:
                  type: string
                  description: 설문조사 색깔
                button_style:
                  type: string
                  description: 버튼 스타일
                main_image_url:
                  type: string
                  description: 메인 이미지 URL
                deadline:
                  type: string
                  format: date-time
                  description: 설문조사 마감 기간
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: 질문 타입 (MULTIPLE_CHOICE, SUBJECTIVE_QUESTION, CHECKBOX, DROPDOWN)
                        enum:
                          - MULTIPLE_CHOICE
                          - SUBJECTIVE_QUESTION
                          - CHECKBOX
                          - DROPDOWN
                      content:
                        type: string
                        description: 질문 내용
                      image_url:
                        type: string
                        description: 질문 관련 이미지 URL
                      choices:
                        type: array
                        items:
                          type: object
                          properties:
                            option:
                              type: string
                              description: 선택지 내용
      responses:
        '201':
          description: 설문조사 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
                  surveyId:
                    type: integer
                    description: 생성된 설문조사의 ID
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
  /api/surveys/{id}/forms:
    get:
      tags:
        - GET
      summary: 폼 모아보기 API
      description: 특정 사용자 ID에 속한 폼 템플릿을 모아서 보여주는 API입니다.
      parameters:
        - name: id
          in: path
          required: true
          description: userId
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 성공적으로 조회됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
                  total_count:
                    type: integer
                    description: 총 설문 템플릿 수
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 오류
  /api/surveys/{id}/join:
    get:
      tags:
        - GET
      summary: Get answered surveys of a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: userId
      responses:
        '200':
          description: A list of surveys answered by the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Survey'
        '404':
          description: No answered surveys found for this user
        '500':
          description: Internal server error
  /api/surveys/{id}:
    put:
      summary: 설문 수정 API
      tags:
        - PUT
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: serveyId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: 사용자 ID
                title:
                  type: string
                  description: 설문조사 제목
                open:
                  type: boolean
                  description: 설문 공개 여부
                font:
                  type: string
                  description: 폰트 설정
                color:
                  type: string
                  description: 설문조사 색깔
                buttonStyle:
                  type: string
                  description: 버튼 스타일
                mainImageUrl:
                  type: string
                  description: 메인 이미지 URL
                deadline:
                  type: string
                  format: date-time
                  description: 설문조사 마감 기간
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: 질문 타입 (MULTIPLE_CHOICE, SUBJECTIVE_QUESTION, CHECKBOX, DROPDOWN)
                        enum:
                          - MULTIPLE_CHOICE
                          - SUBJECTIVE_QUESTION
                          - CHECKBOX
                          - DROPDOWN
                      content:
                        type: string
                        description: 질문 내용
                      imageUrl:
                        type: string
                        description: 질문 관련 이미지 URL
                      choices:
                        type: array
                        items:
                          type: object
                          properties:
                            option:
                              type: string
                              description: 선택지 내용
      responses:
        '200':
          description: 설문 수정 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
                  updatedSurvey:
                    type: object
                    properties:
                      userId:
                        type: integer
                        description: 사용자 ID
                      title:
                        type: string
                        description: 설문조사 제목
                      open:
                        type: boolean
                        description: 설문 공개 여부
                      font:
                        type: string
                        description: 폰트 설정
                      color:
                        type: string
                        description: 설문조사 색깔
                      buttonStyle:
                        type: string
                        description: 버튼 스타일
                      mainImageUrl:
                        type: string
                        description: 메인 이미지 URL
                      deadline:
                        type: string
                        format: date-time
                        description: 설문조사 마감 기간
                      updatedAt:
                        type: string
                        format: date-time
                        description: 설문 수정 시간
        '403':
          description: 접근 및 수정 권한이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '404':
          description: 설문을 찾을 수 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '500':
          description: 설문 수정 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
  /api/surveys/{id}/all:
    get:
      summary: Retrieve a list of surveys
      tags:
        - GET
      description: Retrieve a list of surveys. The response includes a list of surveys and each survey includes its own details along with user's participation status and total user count.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: User ID
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
        - in: query
          name: page
          schema:
            type: integer
          description: The page number
      responses:
        200:
          description: A list of surveys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Survey'
        404:
          description: No surveys found
        500:
          description: Server error
  /api/surveys/{id}/urls:
    get:
      tags:
        - GET
      summary: 설문조사의 URL을 반환합니다.
      description: 특정 설문조사(survey)의 URL을 가져옵니다.
      parameters:
        - in: path
          name: id
          required: true
          description: serveyId
          schema:
            type: integer
      responses:
        '200':
          description: 성공적으로 URL을 가져왔을 때의 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: 'www.asdasdasdasdasd.com/asddasd'
        '404':
          description: 설문조사를 찾을 수 없을 때의 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '설문이 존재하지 않습니다.'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'URL을 생성하는데 실패하였습니다'
    delete:
      summary: 설문 삭제 API
      tags:
        - DELETE
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 삭제할 설문의 ID
      responses:
        '200':
          description: 설문 및 관련 데이터 삭제 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 성공 메시지
        '403':
          description: 설문 삭제 권한이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '404':
          description: 삭제할 설문이 없습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
        '500':
          description: 설문 삭제 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 오류 메시지
components:
  schemas:
    Survey:
      type: object
      required:
        - survey_id
        - title
        - main_image_url
        - created_at
        - updated_at
        - deadline
        - is_attended
        - attend_count
      properties:
        survey_id:
          type: integer
          description: The survey ID
        title:
          type: string
          description: The survey title
        main_image_url:
          type: string
          description: The URL of the survey's main image
        created_at:
          type: string
          format: date-time
          description: The date when the survey was created
        updated_at:
          type: string
          format: date-time
          description: The date when the survey was last updated
        deadline:
          type: string
          format: date-time
          description: The deadline of the survey
        is_attended:
          type: boolean
          description: Whether the user has attended the survey
        attend_count:
          type: integer
          description: The total number of users who have attended the survey
